<?php

declare(strict_types=1);

namespace SymPress\NginxCache\Config;

use Symfony\Component\Filesystem\Filesystem;

final readonly class MultisiteMapGenerator
{
    public function __construct(private Filesystem $filesystem)
    {
    }

    public function generate(): string
    {
        if (!function_exists('is_multisite') || !is_multisite()) {
            return '';
        }
        $sites = get_sites(['network_id' => get_current_network_id(), 'number' => 5001, 'archived' => 0, 'spam' => 0, 'deleted' => 0]);
        if (count($sites) > 5000) {
            throw new \RuntimeException('Multisite map exceeds the 5000-site budget.');
        }
        $entries = [];
        foreach ($sites as $site) {
            $entries[] = ['domain' => (string) $site->domain, 'path' => (string) $site->path, 'blog_id' => (int) $site->blog_id];
        }
        if (function_exists('apply_filters')) {
            $entries = (array) apply_filters('sympress_nginx_cache_multisite_map_entries', $entries);
        }
        return $this->render($entries, is_subdomain_install());
    }

    /** @param array<mixed> $entries */
    public function render(array $entries, bool $subdomains): string
    {
        if (count($entries) > 5000) {
            throw new \RuntimeException('Multisite map exceeds its site budget.');
        }
        $validated = [];
        foreach ($entries as $entry) {
            if (
                !is_array($entry) || !isset($entry['domain'], $entry['path'], $entry['blog_id'])
                || !is_string($entry['domain']) || !is_string($entry['path']) || !is_int($entry['blog_id'])
            ) {
                throw new \RuntimeException('Invalid multisite map entry.');
            }
            $validated[] = $entry;
        }
        usort($validated, static fn (array $first, array $second): int => strlen($second['path']) <=> strlen($first['path']));
        $lines = ['# Generated by SymPress Nginx Cache. Reload Nginx after changes.', 'map ' . ($subdomains ? '$host' : '$uri') . ' $sympress_blog_id {', '    default 0;'];
        $seen = [];
        foreach ($validated as $entry) {
            if (
                $entry['blog_id'] <= 0 || preg_match('/^[A-Za-z0-9.-]+$/D', $entry['domain']) !== 1
                || preg_match('#^/(?:[A-Za-z0-9_~-]+/)*$#D', $entry['path']) !== 1
            ) {
                throw new \RuntimeException('Invalid multisite map entry.');
            }
            $key = $subdomains ? strtolower($entry['domain']) : '~^' . $entry['path'];
            if (isset($seen[$key])) {
                if ($seen[$key] !== $entry['blog_id']) {
                    throw new \RuntimeException('Conflicting multisite map entries.');
                }
                continue;
            }
            $seen[$key] = $entry['blog_id'];
            $lines[] = sprintf('    %s %d;', $key, $entry['blog_id']);
        }
        $lines[] = '}';
        return implode("\n", $lines) . "\n";
    }

    public function refresh(): void
    {
        if (!defined('SYMPRESS_NGINX_CACHE_MULTISITE_MAP_FILE')) {
            return;
        }
        $path = constant('SYMPRESS_NGINX_CACHE_MULTISITE_MAP_FILE');
        try {
            if (
                !is_string($path) || !str_starts_with($path, '/') || !str_ends_with($path, '.conf')
                || str_contains($path, '/..') || preg_match('/[\x00-\x1f\x7f]/', $path) === 1
            ) {
                throw new \RuntimeException('Invalid multisite map destination.');
            }
            for ($parent = $path; $parent !== '/'; $parent = dirname($parent)) {
                if (is_link($parent)) {
                    throw new \RuntimeException('Symlink map destinations are forbidden.');
                }
            }
            $map = $this->generate();
            if ($map === '') {
                return;
            }
            // dumpFile atomically replaces only the explicitly configured .conf file.
            // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Compare the explicitly configured local map before atomic replacement.
            if (!is_file($path) || file_get_contents($path) !== $map) {
                $this->filesystem->dumpFile($path, $map);
            }
            delete_site_transient('sympress_nginx_cache_multisite_map_error');
        } catch (\Throwable) {
            set_site_transient('sympress_nginx_cache_multisite_map_error', 'Multisite map was not updated; check the configured path, site data and permissions. The previous file is retained.', HOUR_IN_SECONDS);
        }
    }
}
