<?php

declare(strict_types=1);

namespace SymPress\NginxCache\Config;

use SymPress\NginxCache\Key\CacheKeyStrategy;
use SymPress\NginxCache\Settings\WordPressCacheSettings;
use SymPress\NginxCache\Value\CacheProfile;

final readonly class NginxConfigGenerator
{
    public function __construct(
        private WordPressCacheSettings $settings,
        private BypassRuleProvider $rules,
        private CacheKeyStrategy $keys,
    ) {
    }

    public function generate(?CacheProfile $profile = null): string
    {
        $profile ??= $this->settings->profile();
        $rules = $this->rules->rules($profile);
        $lines = [
            '# Generated by SymPress Nginx Cache.',
            sprintf('# Profile: %s.', $profile->value),
            '# Review paths, zone size and the PHP location include before deploying.',
            sprintf('fastcgi_cache_path %s levels=%s keys_zone=WORDPRESS:100m inactive=60m max_size=256m use_temp_path=off;', $this->settings->cachePath(), $this->settings->cacheLevels()),
            '',
            'map $http_user_agent $sympress_cache_device {',
            '    default desktop;',
            '    ~*(Mobile|Android|Silk/|Kindle|BlackBerry|Opera\\ Mini|Opera\\ Mobi) mobile;',
            '}',
            '',
            'map $http_user_agent $sympress_cache_skip_user_agent {',
            '    default 0;',
        ];

        foreach ($this->safePatterns($rules['user_agents']) as $pattern) {
            $lines[] = sprintf('    ~*%s 1;', $pattern);
        }

        $lines = [
            ...$lines,
            '}',
            '',
            'map $request_method $sympress_cache_skip_method {',
            '    default 1;',
            '    GET 0;',
            '    HEAD 0;',
            '}',
            '',
            'map $query_string $sympress_cache_skip_query {',
            '    default 1;',
        ];

        foreach ($this->safePatterns($rules['query_allowlist']) as $pattern) {
            $lines[] = sprintf('    ~%s 0;', $pattern);
        }

        $lines = [
            ...$lines,
            '}',
            '',
            'map $request_uri $sympress_cache_skip_uri {',
            '    default 0;',
        ];

        foreach ($this->safePatterns($rules['uris']) as $pattern) {
            $lines[] = sprintf('    ~*%s 1;', $pattern);
        }

        $lines = [
            ...$lines,
            '}',
            '',
            'map $http_cookie $sympress_cache_skip_cookie {',
            '    default 0;',
        ];

        foreach ($this->safePatterns($rules['cookies']) as $pattern) {
            $lines[] = sprintf('    ~*%s 1;', $pattern);
        }

        return implode("\n", [
            ...$lines,
            '}',
            '',
            'map $http_authorization $sympress_cache_skip_authorization {',
            '    default 1;',
            '    "" 0;',
            '}',
            '',
            'map "$sympress_cache_skip_method$sympress_cache_skip_query$sympress_cache_skip_uri$sympress_cache_skip_cookie$sympress_cache_skip_user_agent$sympress_cache_skip_authorization" $sympress_cache_skip {',
            '    default 1;',
            '    "000000" 0;',
            '}',
            '',
            '# Add inside the server block before the PHP/FastCGI location:',
            'location ~* \.(?:avif|css|eot|gif|ico|jpe?g|js|json|mjs|mp4|ogg|otf|png|svg|ttf|webm|webp|woff2?)$ {',
            '    expires 1y;',
            '    add_header Cache-Control "public, max-age=31536000, immutable" always;',
            '    access_log off;',
            '    try_files $uri =404;',
            '}',
            '',
            '# Add inside the PHP/FastCGI location:',
            'fastcgi_cache WORDPRESS;',
            sprintf('fastcgi_cache_key "%s";', $this->keys->template()),
            '# Optional mobile/desktop variants: append |$sympress_cache_device to fastcgi_cache_key and keep purge tooling in sync via sympress_nginx_cache_key_candidates.',
            'fastcgi_cache_bypass $sympress_cache_skip;',
            'fastcgi_no_cache $sympress_cache_skip $upstream_http_set_cookie $upstream_http_x_accel_expires;',
            'fastcgi_cache_methods GET HEAD;',
            'fastcgi_cache_valid 200 301 10m;',
            'fastcgi_cache_valid 404 1m;',
            'fastcgi_cache_lock on;',
            'fastcgi_cache_lock_timeout 10s;',
            'fastcgi_cache_lock_age 10s;',
            'fastcgi_cache_background_update on;',
            'fastcgi_cache_use_stale error timeout invalid_header updating http_500 http_503;',
            'add_header X-Nginx-Cache $upstream_cache_status always;',
            'add_header X-SymPress-Cache-Skip $sympress_cache_skip always;',
            '# Optional diagnostics only: add_header X-SymPress-Cache-Key "$scheme|$request_method|$host|$request_uri" always;',
            '',
            '# WordPress emits Surrogate-Key / X-SymPress-Cache-Tags when debug headers are enabled.',
            '# With Cloudflare enabled it also emits Cache-Tag for purge-by-tag support.',
            '# These headers can be consumed by NGINX Plus, OpenResty/Lua, njs, a sidecar agent, a CDN or a Redis-backed purge worker.',
            '',
            '# Optional secured local purge endpoint for NGINX Plus or compatible purge modules:',
            '# location = /__sympress-nginx-cache-purge-all {',
            '#     allow 127.0.0.1;',
            '#     deny all;',
            '#     # Configure SYMPRESS_NGINX_CACHE_FULL_PURGE_MODE=endpoint and point',
            '#     # SYMPRESS_NGINX_CACHE_FULL_PURGE_ENDPOINT at this internal URL.',
            '#     # NGINX Plus: fastcgi_cache_purge WORDPRESS "*";',
            '#     # ngx_cache_purge-compatible modules may use their own wildcard syntax.',
            '# }',
            '',
        ]);
    }

    /** @return list<string> */
    public function validate(string $config): array
    {
        $required = [
            'fastcgi_cache_path',
            'fastcgi_cache_key',
            'fastcgi_cache_bypass',
            'fastcgi_no_cache',
            'fastcgi_cache_valid',
        ];
        $missing = [];

        foreach ($required as $directive) {
            if (str_contains($config, $directive)) {
                continue;
            }

            $missing[] = $directive;
        }

        return $missing;
    }

    /**
     * @param list<string> $patterns
     * @return list<string>
     */
    private function safePatterns(array $patterns): array
    {
        return array_values(
            array_filter(
                $patterns,
                static fn (string $pattern): bool => $pattern !== '' && !str_contains($pattern, "\n") && !str_contains($pattern, "\r") && !str_contains($pattern, ';') && !str_contains($pattern, '{') && !str_contains($pattern, '}'),
            ),
        );
    }
}
